### ISSUE TITLE
Question regard rules!

### ISSUE THREAD

**Issue by multfaciladm** [ismailtasdelen/Anti-DDOS#6]
Hi there!

The question is: If I have in other file some iptables rules running like open some port or permit just one IP to connect, etc, When I start this script, it will overlap my others rules? Or need I concat both?

Thanks.

**Comment by ismailtasdelen** [comment]
Hello,

You should configure the config file according to your network and system infrastructure. Iptables rules are explicitly stated.

Thanks

**Comment by multfaciladm** [comment]
Ok got it.

Thanks.
