### ISSUE TITLE
I may be retarded, but...

### ISSUE THREAD

**Issue by shoot** [ismailtasdelen/Anti-DDOS#8]
After I ran the script I cant login to SSH anymore it just says connection refused.

**Comment by ismailtasdelen** [comment]
Check the configuration. This may be a problem with your SSH configuration. Or the SSH boards within the Anti-DDOS script may be blocking this. Because this type of blocking rules are included. Never run this script directly, your adapt to your own system.

**Comment by lynggo** [comment]
All port to be blocked, only http port 80 can be accessed.
how to make another port ex 8888 icecast stream enable with this rule anti-DDOS

Tks

**Comment by ramboi234** [comment]
same pls devv, how to uninstall thissssss

**Comment by debian-user-france1** [comment]
Don't run things when do don't know if it is working
