### ISSUE TITLE
Blocking IPV6?

### ISSUE THREAD

**Issue by Lvl4Sword** [ismailtasdelen/Anti-DDOS#9]
Perhaps I'm confused, but how does this ~~prevent~~ **protect** against a denial of service attack?

**Comment by ismailtasdelen** [comment]
Of course, it writes iptables rules on the linux system side to prevent packet requests.

**Comment by Lvl4Sword** [comment]
I'm not sure you understand. I have systems that have both IPV4 and IPV6. Using this script would prevent those systems from being accessible though IPV6.

**Comment by ismailtasdelen** [comment]
The rules for IPv6 and IPv4 are included in the script. But when using these scripts you have to adapt them to your own system. And you're right about one thing. There is not enough sample script for ipv6 here. I'il be uptade soon.

**Comment by lynggo** [comment]
All port to be blocked, only http port 80 can be accessed.
how to make another port ex 8888 icecast stream enable with this rule anti-DDOS

Tks

**Comment by ismailtasdelen** [comment]
Man, you should apply these configurations according to your system architecture, I warned you.

**Comment by Lvl4Sword** [comment]
Why was this issue closed?

**Comment by ismailtasdelen** [comment]
Ipv6 rules to be added

**Comment by Lvl4Sword** [comment]
Had me incredibly confused, considering I was never warned about anything.
Do you need assistance with anything in regards to this?

**Comment by ismailtasdelen** [comment]
Not for the moment.

**Comment by Lvl4Sword** [comment]
Saw you closed it again, was this on purpose?
